version: '3'

services:
  nginx-php56:
    image: nginx
    ports:
        - "10056:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default56.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php56
  nginx-php73:
    image: nginx
    ports:
        - "10073:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default73.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php56
  php56:
    build:
      context: .
      dockerfile: ./docker/Dockerfile56
    volumes:
      - ./app:/var/www/app
    depends_on:
      - memcached
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
  php73:
    build:
      context: .
      dockerfile: ./docker/Dockerfile73
    volumes:
      - ./app:/var/www/app
    depends_on:
      - memcached
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
  memcached:
    image: memcached