version: '3'

services:
  nginx-php56:
    image: nginx
    ports:
        - "10056:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/php56/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php56/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php56
  nginx-php73:
    image: nginx
    ports:
        - "10073:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/php73/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php73/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php56
  php56:
    build: ./docker/php56
    volumes:
      - ./app:/var/www/app
    depends_on:
      - memcached
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
  php73:
    build: ./docker/php73
    volumes:
      - ./app:/var/www/app
    depends_on:
      - memcached
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
  memcached:
    image: memcached