version: '3'

services:
  nginx-php56:
    image: nginx
    ports:
        - "10056:80"
    volumes:
      - ./app:/var/www/app
      - ./nginx/default56.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php56
  nginx-php73:
    image: nginx
    ports:
        - "10073:80"
    volumes:
      - ./app:/var/www/app
      - ./nginx/default73.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php56
  php56:
    image: php:5.6-fpm-stretch
    volumes:
      - ./app:/var/www/app
    depends_on:
      - memcached
  php73:
    image: php:7.3-fpm-stretch
    volumes:
      - ./app:/var/www/app
    depends_on:
      - memcached
  memcached:
    image: memcached